Shift test numeration and add gym parsing
mratkovic/codeforces-parser pull request #1
Opened 2020-08-31 19:54 UTC by julianferres

Hi! I consider that test should start in 1 (to be more user friendly). Also added gym parsing, since it was only needed to add a parameter

2020-09-01 05:20 UTC, mratkovic requested changes
Awesome, thanks for the update 👍 

rest of the PR looks good to me

2020-09-01 05:20 UTC, mratkovic commented on cfparser.py
> +        # , TESTS_SUBDIR)
Is this comment needed?

2020-09-01 05:29 UTC, mratkovic commented
@julianferres, also please update examples and usage sections in README.md with added contest type argument

2020-09-02 22:33 UTC, julianferres commented
Done

2020-09-03 06:31 UTC, mratkovic approved these changes

2020-09-03 06:33 UTC, merged